name: sysfoo-githubactions-pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Hello sys-foo application"
        
      - name: code-checkout
        uses: actions/checkout@v6.0.2
        
      - name: maven-test
        run: mvn test
        
      - name: maven-clean
        run: mvn clean
        
      - name: maven-package
        run: mvn package

      - name: maven-packaging-warfile-list
        run: ls -lrt target

      - name: upload-artifact
        run: actions/upload-artifact@v6.0.0
        with:
          name: sysfoo-artifact
          path: target/*.war
          
